### ISSUE TITLE
存储csv 文件，汉字总是乱码

### ISSUE THREAD

**Issue by Pythonpa** [rieuse/learnPython#1]
```
# -*- coding:utf-8 -*-

from bs4 import BeautifulSoup
import requests
import csv

html = "http://www.meilele.com/category-chuangdian/"
headers = {
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'}
res = requests.get(html,headers=headers)
res.raise_for_status()
res.encoding = res.apparent_encoding
soup = BeautifulSoup(res.text,'lxml')

result = []
for i in range(len(soup.find_all('span',{"class":"m-count JS_async_price"}))):
    goods_ID = soup.find_all('span',{"class":"m-count JS_async_price"})[i]["data-goods_id"]
    goods_Price = soup.find_all('span',{"class":"m-count JS_async_price"})[i].get_text()
    goods_Name = soup.find_all('a',{"class":"d-name"})[i].text.strip()
    result.append((goods_ID,goods_Price,goods_Name))

    with open('美乐乐床垫列表.csv','w',newline='',encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(('商品ID','商品价格','商品名称'))
        for r in result:
            writer.writerow(r)
```
如代码，请问下博主，你有没有遇到这类问题，我网上找了很多种办法，比encode等，都不行....csv文件中的汉字，都是乱码.........
        还请指教~~

**Comment by rieuse** [comment]
你这个用notepad打开没问题。


商品ID,商品价格,商品名称
83543,3299.00,[喜临门·睡美人] 【Clover克罗弗】超值推荐款 1.5/1.8米经典软硬双面两用床垫 天然乳胶环保床垫【暑价特惠】3D椰棕+天然乳胶，软硬双面，独立静音！6.29-7.9自营商品满6千减500享五包！更有喜临门&艾玛诗床垫全场两件88折！更多优惠戳>>>
36965,9839.00,[艾玛诗] 【星宿】全3D内胆高弹透气床垫 尖端3D科技 可全拆洗 1.8*2.0米双面（需放在床板上使用）【暑价特惠】6.29-7.9喜临门艾玛诗床垫两件88折疯抢，自营商品满6000减500双重优惠，狂欢全场！更有品牌特惠不容错过！更多床垫精品冰点价，戳>>>
236888,3999.00,[顾家1号垫] 【1号垫•深睡版】1.2/1.5/1.8/2.0/2.2米弹簧床垫 双面使用 天然乳胶 独立袋装弹簧床垫 互不干扰 清爽透气 【暑价特惠】天然乳胶床垫，安全环保，促眠安神！6.29-7.9美乐乐自营满6000减500，享5包！抢爆款凭券更享满减优惠！更有扫地机器人免费抽！猛戳>>>
244605,5199.00,[喜临门·睡美人] 【Hey美人】1.8*2.0米七区独立弹簧床垫 比利时“随时控“面料 天然乳胶 防螨海绵 记忆海绵 两公分3D材料层【暑价特惠】天然乳胶，深度贴合，呵护脊椎健康！6.29-7.9日喜临门艾玛诗床垫两件88折疯抢，自营商品满6000减500狂欢全场！更有爆款专享券，限量疯抢！格力空调免费抽！戳>>>

**Comment by rieuse** [comment]
你也可以试试使用notepad++把它转码成ansi编码，然后使用excel打开应该就没了乱码了。

**Comment by Pythonpa** [comment]
谢谢，我用的IDE是pycharm，然后，后面发现，通过 encoding='gb18030'解决了，之前我是用的‘utf-8’

2017-07-09 8:30 GMT+08:00 布咯咯_rieuse <notifications@github.com>:

**Comment by Pythonpa** [comment]
谢谢，我用的IDE是pycharm，然后，后面发现，通过 encoding='gb18030'解决了，之前我是用的‘utf-8’

在 2017年7月8日 下午1:16，布咯咯_rieuse <notifications@github.com>写道：
